# Generated by Django 3.2.15 on 2022-08-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donate',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
